version: '3'

services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: ${APP_NAME}-nginx
        restart: always
        volumes:
            - ./sources:/var/www/html
            - ./nginx/logs:/var/log/nginx
            - ./nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8000:80"
            - "443:443"
        depends_on:
            - php
            - mysql
        links:
            - php
        command: nginx -g 'daemon off;'
        networks:
            - lemp-network

    php:
        build:
            context: ./php
            dockerfile: Dockerfile
        container_name: ${APP_NAME}-php
        restart: always
        depends_on:
            - mysql
        links:
            - mysql
        volumes:
            - ./sources:/var/www/html
            - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
        ports:
            - "9000:9000"  
        networks:
            - lemp-network
            
    mysql:
        build:
            context: ./mysql
            dockerfile: Dockerfile
        container_name: ${APP_NAME}-mysql
        restart: always
        volumes:
            - dbdata:/var/lib/mysql
            - ${MYSQL_CONFIG_PATH}:/etc/mysql/conf.d
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            - lemp-network

    phpmyadmin:
        build:
            context: ./pma
            dockerfile: Dockerfile
        container_name: ${APP_NAME}-phpmyadmin
        ports:
            - ${PMA_PORT}:80
        depends_on:
            - mysql
        environment:
            - PMA_HOST=${MYSQL_HOST}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            - lemp-network

networks:
    lemp-network:
        driver: bridge

volumes:
    dbdata:
        driver: local