version: '3'

services:
    nginx:
        container_name: ${APP_NAME}-nginx
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
            - ${APPLICATION}:/var/www/html
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        links:
            - php
        networks:
            - lemp-network

    php:
        container_name: ${APP_NAME}-php
        restart: always
        build:
            context: ./php
            args:
                - INSTALL_GD=${PHP_FPM_INSTALL_GD}
                - INSTALL_MBSTRING=${PHP_FPM_INSTALL_MBSTRING}
                - INSTALL_MCRYPT=${PHP_FPM_INSTALL_MCRYPT}
                - INSTALL_PDO_MYSQL=${PHP_FPM_INSTALL_PDO_MYSQL}
                - INSTALL_PDO_POSTGRESQL=${PHP_FPM_INSTALL_PDO_POSTGRESQL}
                - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
                - INSTALL_COMPOSER=${PHP_FPM_INSTALL_COMPOSER}
            dockerfile: Dockerfile
        expose:
            - "9000"    
        volumes:
            - ${APPLICATION}:/var/www/html
        networks:
            - lemp-network            
            
    mysql:
        container_name: ${APP_NAME}-mysql
        restart: always
        build:
            context: ./mysql
            dockerfile: Dockerfile
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - ${MYSQL_DATA}:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            - lemp-network

    phpmyadmin:
        container_name: ${APP_NAME}-phpmyadmin
        build:
            context: ./pma
            dockerfile: Dockerfile
        ports:
            - ${PMA_PORT}:80
        links:
            - mysql
        environment:
            - PMA_HOST=${MYSQL_HOST}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            - lemp-network

networks:
    lemp-network:
        driver: bridge