version: '3'

services:
    web:
        build:
            context: .
            dockerfile: web.Dockerfile
        # container_name: ${APP_NAME}-web
        restart: always
        # volumes:
        #     - ${APPLICATION}:${DOCUMENT_ROOT}
        ports:
            - "80:80"
            - "443:443"
        links:
            - fpm
        # networks:
        #     - lemp-network

    fpm:
        build:
            context: .
            dockerfile: fpm.Dockerfile
        # container_name: ${APP_NAME}-fpm
        restart: always
        # volumes:
        #     - ${APPLICATION}:${DOCUMENT_ROOT}
        ports:
            - "9000:9000"  
        links:
            - mysql  
        # networks:
        #     - lemp-network
            
    mysql:
        image: mysql:5.7
        # container_name: ${APP_NAME}-mysql
        restart: always
        # volumes:
            # - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        # command: [
        #     '--character-set-server=utf8mb4', 
        #     '--collation-server=utf8mb4_unicode_ci',
        #     '--default-authentication-plugin=mysql_native_password']
        environment:
            - MYSQL_USER=thachvu
            - MYSQL_PASSWORD=thachvu
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=thachvu
        # networks:
        #     - lemp-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        # container_name: ${APP_NAME}-phpmyadmin
        ports:
            - 8080:80
        links:
            - mysql
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
            - MYSQL_ROOT_PASSWORD=root
        # networks:
        #     - lemp-network

# networks:
#     lemp-network:
#         driver: bridge

# volumes:
#     dbdata:
#         driver: local